config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "toppages#index"
  get 'themes/index'
  get 'themes/if'
  resources :users, only: [:index, :new]
  resources :liberty_titles, only: [:index, :new, :create, :destoy] do
    resources :liberty_comments, only: [:index, :new, :create]
  end
  resources :occupation_titles, only: [:index, :new, :create, :destoy] do
    resources :occupation_comments, only: [:index, :new, :create]
  end
  resources :money_titles, only: [:index, :new, :create, :destoy] do
    resources :money_comments, only: [:index, :new, :create]
  end
  resources :happiness_titles, only: [:index, :new, :create, :destoy] do
    resources :happiness_comments, only: [:index, :new, :create]
  end
  resources :human_titles, only: [:index, :new, :create, :destoy] do
    resources :human_comments, only: [:index, :new, :create]
  end
  resources :fortune_titles, only: [:index, :new, :create, :destoy] do
    resources :fortune_comments, only: [:index, :new, :create]
  end
  resources :death_titles, only: [:index, :new, :create, :destoy] do
    resources :death_comments, only: [:index, :new, :create]
  end
  resources :illness_titles, only: [:index, :new, :create, :destoy] do
    resources :illness_comments, only: [:index, :new, :create]
  end
  resources :emotion_titles, only: [:index, :new, :create, :destoy] do
    resources :emotion_comments, only: [:index, :new, :create]
  end
  resources :success_titles, only: [:index, :new, :create, :destoy] do
    resources :success_comments, only: [:index, :new, :create]
  end
  resources :love_titles, only: [:index, :new, :create, :destoy] do
    resources :love_comments, only: [:index, :new, :create]
  end
  resources :lifestyle_titles, only: [:index, :new, :create, :destoy] do
    resources :lifestyle_comments, only: [:index, :new, :create]
  end
  resources :life_titles, only: [:index, :new, :create, :destoy] do
    resources :life_comments, only: [:index, :new, :create]
  end
  resources :values_titles, only: [:index, :new, :create, :destoy] do
    resources :values_comments, only: [:index, :new, :create]
  end
  resources :hope_titles, only: [:index, :new, :create, :destoy] do
    resources :hope_comments, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :title

  validates :comment, presence: true, length: { maximum: 100 }
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/theme.rb
class Theme < ActiveHash::Base
  self.data = [
    { id: 1, name: '自由' },
    { id: 2, name: '仕事' },
    { id: 3, name: 'お金' },
    { id: 4, name: '幸せ' },
    { id: 5, name: '人間' },
    { id: 6, name: '運' },
    { id: 7, name: '死' },
    { id: 8, name: '病気' },
    { id: 9, name: '感情' },
    { id: 10, name: '成功' },
    { id: 11, name: '愛' },
    { id: 12, name: '人生' },
    { id: 13, name: '命' },
    { id: 14, name: '価値観' },
    { id: 15, name: '希望' }
  ]
end

app/models/title.rb
class Title < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true, length: { maximum: 38 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  has_many :titles
  has_many :comments
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )

    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

  validates :nickname, presence: true
end

app/controllers/occupation_titles_controller.rb
class OccupationTitlesController < ApplicationController
  before_action :move_to_sign_up, only: [:create]

  def index
    @titles = Title.where(theme_id: 2).order('created_at DESC')
    # Model.joins(:other_table).order('other_tables.updated_at desc,models.created_at desc')
  end

  def new
    @title = Title.new
  end

  def create
    @title = Title.new(occupation_title_params)
    if @title.save
      # binding.pry
      redirect_to occupation_titles_path
    else
      render :new
    end
  end
end

private

def occupation_title_params
  params.require(:title).permit(:title).merge(theme_id: 2, user_id: current_user.id)
end

def move_to_sign_up
  redirect_to new_user_registration_path unless user_signed_in?
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/death_titles_helper.rb
module DeathTitlesHelper
end

app/helpers/hope_comments_helper.rb
module HopeCommentsHelper
end

app/helpers/hope_titles_helper.rb
module HopeTitlesHelper
end

app/helpers/human_titles_helper.rb
module HumanTitlesHelper
end

app/helpers/life_comments_helper.rb
module LifeCommentsHelper
end

app/helpers/life_titles_helper.rb
module LifeTitlesHelper
end

app/helpers/love_titles_helper.rb
module LoveTitlesHelper
end

app/helpers/money_titles_helper.rb
module MoneyTitlesHelper
end

app/helpers/occupation_titles_helper.rb
module OccupationTitlesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/occupation_titles/index.html.erb
<% breadcrumb :occupation_titles %>
<div class='all'>
    <span class='question'>
    仕事とはなにか
    </span>

  <div class='topic'>

    職業<br>
    労働<br>
    仕事 (物理学) - 物理学における物理量。<br>
    仕事 (熱力学) - 熱力学における力学的なエネルギー。<br>
    仕事 (電気) - 電場中の電荷がする仕事。<br>
    電力量 - 電気回路における電気エネルギー。<br>
    仕事 (企業) - 日本の芸能事務所。株式会社仕事。旧俳優座映画放送。<br>
    （wikipedia）</p><br>

    何かを作り出す、または、成し遂げるための行動。<br>
    生計を立てる手段として従事する事柄。職業。<br>
    したこと。行動の結果。業績。<br>
    悪事をしたり、たくらんだりすること。しわざ。所業。<br>
    《「針仕事」の略》縫い物。裁縫。<br>
    力学で、物体が外力の作用で移動したときの、移動方向への力の成分と移動距離との積。<br>単位はエネルギーの単位ジュール、その他ワット秒・ワット時など。<br>
    （goo辞書）</p><br>
    
  </div>
  <br>
  <span class='teach'>あなたの哲学を教えてください</span><br>
  <div class="create-title">
    <a href="/occupation_titles/new">新たなお題で哲学する</a>
  </div>
  <br>
  <div class="titles">
    <% @titles.each do |title| %>
      <div class="title">
        <div class="title-name">
          <%= link_to title.title, occupation_title_occupation_comments_path(title), class: "title-title" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/occupation_titles/new.html.erb
<% breadcrumb :new_occupation_title %>
<div class='new-title-container'>
  <div class='teach'>新たに哲学するお題をどうぞ</div>
  <%=form_with model: @title, url:occupation_titles_path, local: true do |f|%>
  <div><%= f.text_area :title, class: 'text_area', placeholder: 'このアウトプットから何か新しい人生が始まるかもしれません（38文字まで入力できます）'%></div>
  <div><%= f.submit "作成する", class: 'title_btn'%></div>
  <% end %>
</div>